CMS_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("cms.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.urls import path

from .views import IndexPageView, ProductDetailView, SendEmailView

urlpatterns = [

    path('', IndexPageView.as_view(), name="index"),
    path('<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('send_email', SendEmailView.as_view(), name="send_email"),

]

cms/models.py
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, MinValueValidator
from django.db import models
from django.urls import reverse


def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2000000
    if filesize > megabyte_limit:
        raise ValidationError("Размер файла не может быть больше 2Мб" % str(megabyte_limit))


class IndexPage(models.Model):
    page_title = models.CharField("Заголовок страницы", max_length=256)
    keywords = models.TextField("Ключевые слова", blank=True, null=True)
    description = models.TextField("Описание", blank=True, null=True)
    headline = models.CharField("Заголовок текста главной страницы", max_length=256, blank=True, null=True)
    latitude = models.DecimalField("Широта", max_digits=4, decimal_places=2, blank=True, null=True,
                                   validators=[MinValueValidator(0)])
    longitude = models.DecimalField("Долгота", max_digits=4, decimal_places=2, blank=True, null=True,
                                    validators=[MinValueValidator(0)])
    photo_width = models.PositiveIntegerField("Ширина фото слайдера", default=1240, null=True, blank=True)
    photo_height = models.PositiveIntegerField("Высота фото слайдера", default=833, null=True, blank=True)

    class Meta:
        verbose_name = "Главная страница сайта"
        verbose_name_plural = "Редактирование главной страницы"

    def __str__(self):
        return "Редактировать"


class Photo(models.Model):
    headline = models.ForeignKey(IndexPage, verbose_name="Главная страница", on_delete=models.CASCADE)
    image = models.ImageField("Фотография слайдера главной страницы", upload_to='sliders/',
                              validators=[validate_image, FileExtensionValidator(['jpg', 'jpeg'])])
    name = models.CharField("Название фотографии", max_length=256)

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"


class Paragraph(models.Model):
    text = models.TextField("Текст")
    headline = models.ForeignKey(IndexPage, verbose_name="Главная страница", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Абзац"
        verbose_name_plural = "Абзацы"


class Product(models.Model):
    page_title = models.CharField("Заголовок страницы", max_length=256)
    keywords = models.TextField("Ключевые слова", blank=True, null=True)
    description = models.TextField("Описание", blank=True, null=True)
    name = models.CharField("Название продукта", max_length=256, blank=True, null=True)
    created = models.DateTimeField("Дата и время добавления", auto_now_add=True)
    photo = models.ImageField("Фотография продукта", upload_to='products/', blank=True, null=True,
                              validators=[validate_image, FileExtensionValidator(['jpg', 'jpeg'])])
    photo_width = models.PositiveIntegerField("Ширина фотографии", default=1240, null=True, blank=True)
    photo_height = models.PositiveIntegerField("Высота фотографии", default=992, null=True, blank=True)
    url = models.SlugField("Ссылка", max_length=130, unique=True)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Редактирование продуктов"

    def __str__(self):
        return self.url

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"slug": self.url})


class Option(models.Model):
    title = models.CharField("Заголовок списка опций", max_length=256)
    product = models.ForeignKey(Product, verbose_name="Продукт", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Заголовок списка опций"
        verbose_name_plural = "Заголовки списков опций"

    def __str__(self):
        return ''


class Suboption(models.Model):
    text = models.TextField("Пункт списка")
    option = models.ForeignKey(Option, verbose_name="Опции", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Пункт списка"
        verbose_name_plural = "Пункты списка"

    def __str__(self):
        return ''

cms/forms.py
from django import forms


class EmailForm(forms.Form):
    name = forms.CharField(label='Ваше имя', required=True)
    email = forms.EmailField(label='Электронная почта', required=True)

cms/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from .models import IndexPage, Product
from .forms import EmailForm
from .service import send_message


class IndexPageView(ListView):
    context_object_name = 'products'
    queryset = Product.objects.all().order_by('created')
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['page'] = IndexPage.objects.first()
        context['form'] = EmailForm()
        return context


class ProductDetailView(DetailView):
    model = Product
    slug_field = "url"


class SendEmailView(View):
    def post(self, request):
        form = EmailForm(request.POST)
        if form.is_valid():
            send_message(form.cleaned_data['email'])
        return redirect(reverse('index'))

templates/cms/product_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>{{ product.page_title }}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>
<div class="wrapper">
    <div>
        <div class="content">
            <div>
                <a href="{% url "index" %}" class="go-back">На главную</a>
                {% if product.name %}
                    <h1>{{ product.name }}</h1>
                {% endif %}
                {% if product.photo %}
                    <img src="{{ product.photo.url }}" width="{{ product.photo_width }}"
                         height="{{ product.photo_height }}" alt="{{ product.name }}">
                {% endif %}
                <div class="product-info">
                    {% for list in product.option_set.all %}
                        <div class="product-info-item">
                            <h2>{{ list.title }}</h2>
                            <ul>
                                {% for item in list.suboption_set.all %}
                                    <li>{{ item.text }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
</body>
</html>

templates/cms/product_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no, viewport-fit=cover">
    <meta name="keywords" content={{ page.keywords }}>
    <meta name="description" content={{ page.description }}>
    <title>{{ page.page_title }}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Piazzolla:wght@400;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href={% static 'css/swiper-bundle.min.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>
<div class="wrapper">
    <div class="content">
        {% if page.headline %}
            <h1>{{ page.headline }}</h1>
        {% endif %}
        <div class="swiper-container">
            <div class="swiper-wrapper">
                {% for photo in page.photo_set.all %}
                    <div class="swiper-slide"><img src="{{ photo.image.url }}" width="50" height="50"
                                                   alt="{{ photo.name }}"></div>
                {% endfor %}
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
        <div class="intro-text">
            {% for paragraph in page.paragraph_set.all %}
                <p>{{ paragraph.text }}</p>
            {% endfor %}
        </div>
        <div class="products-list">
            <h2>Продукты</h2>
            <ul>
                {% for product in products %}
                    <li><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div id="map" data-latitude="{{ page.latitude }}" data-longitude="{{ page.longitude }}"></div>
        <h2>Отправить сообщение</h2>
        <form action="{% url 'send_email' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=28ba27e6-8179-45dd-8a90-a542e1883e67"
        type="text/javascript"></script>
<script src={% static 'js/swiper-bundle.min.js' %}></script>
<script src={% static 'js/main.js' %}></script>
</body>
</html>